[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "libc6-compat"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy ./node_modules/.bin/prisma generate",
  "./node_modules/.bin/next build"
]

[start]
cmd = "node node_modules/prisma/build/index.js db push --accept-data-loss && ./node_modules/.bin/next start -p ${PORT:-3000}"
