[build]
builder = "nixpacks"
buildCommand = "npm run build && ./node_modules/.bin/prisma db push --accept-data-loss"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
